#
# Here are all Functions, that check the common parameters used by the algorithms
#


#' @name check_v
#' @title Check parameter v
#' @description
#' Check parameter v for validity. V must not be NULL and it has to be a function
#' @template author/EW
#' @template param/v
#' @return Returns
#'
#' example
#' check_v(function(x)x)
check_v <- function(v) {

  if(is.null(v))
    stop("Function is NULL")

  if(!is.function(v))
    stop("Parameter v isn't a function")

}





#' @name check_positive_number
#' @title Check if the parameter is a number and positive
#' @description
#' Check if the parameter is a number and positive. It can be used for the parameter
#' n, i, m and w.
#' @template author/EW
#' @template param/i
#' @return Returns
check_positive_number <- function(parameter) {

  if(is.null(parameter))
    stop("number is NULL")

  if(!is.numeric(parameter))
    stop("number must be a number")

  if(parameter <= 0)
    stop("number must be greater than 0")

}






#' @name check_n_i
#' @title Check parameter n and i
#' @description
#' Check parameter n and i for validity with the intended functions for that purpose.
#' Additionally it checks if i is smaller or equal n, because player i must be in the quantity
#' generated by n.
#' @template author/EW
#' @template param/n
#' @template param/i
#' @return Returns
check_n_i <- function(n, i) {
  check_positive_number(n)
  check_positive_number(i)

  if(i > n)
    stop("i isn't in n")

}





#' @name check_P
#' @title Check parameter P
#' @description
#' Check parameter P for validity. Parameter P must not be NULL, must be a
#' list of vectors or a list of lists for the priori unions. The priori unions
#' must be numeric and positive. Besides the priori unions has to be disjunct.
#' @template author/EW
#' @template param/P
#' @return Returns
check_P <- function(P) {

  # if P is set
  if(is.null(P))
    stop("P is NULL")

  # Check if it is a list
  if(!is.list(P))
    stop("Priori unions must be a list")

  #Check if the values of the priori unions are numeric and positive
  if(any(sapply(unlist(P), function(x) is.numeric(x) && x > 0) == FALSE))
    stop("There is a priori union that contains a element that isn't numeric or smaller than 0")

  #Check if the prior unions are disjunct
  last = -1
  liste = sort(unlist(P))
  for(p in liste) {
    if(p != last) last = p
    else stop("Priori unions aren't disjunct")
  }

}






#' @name check_P_i
#' @title Check parameter P and i
#' @description
#' Check parameter P and i for validity with the intended functions for that purpose.
#' Additionally it checks if player i is element of a priori union in P
#' @template author/EW
#' @template param/P
#' @template param/i
#' @return Returns
check_P_i <- function(P, i) {
  check_P(P)
  check_positive_number(i)

  if(i %in% unlist(P) == FALSE)
    stop("i isn't in a priori unions")

}


